# Generated by Django 4.2.1 on 2023-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_countries_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True,
                default="noname",
                max_length=100,
                verbose_name="Name of User",
            ),
            preserve_default=False,
        ),
    ]
